version: '3.3'

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file: variables.env
  app:
    image: diasdra/demo4640app:latest
    depends_on:
      - db
    env_file: variables.env
  web:
    image: diasdra/demo4640web:latest
    depends_on:
      - db
    ports:
      - 8080:80
    env_file: variables.env
  insert:
    build:
      dockerfile: ./insert/Dockerfile
    env_file: variables.env